### ISSUE TITLE
local maven mirror

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#13]
dbuild generates a lot of traffic to maven/ivy repos. To speed up the build, we should proxy & cache them. Can we use a regular http proxy like squid (which can even be transparent using NAT) instead of a full blown artifactory install?

**Comment by cunei** [comment]
@adriaanm, using squid will probably not work well as soon as you start using snapshots, I think. That may be the main limitation.

**Comment by adriaanm** [comment]
good point!

**Comment by cunei** [comment]
@adriaanm, Using artifactory as a Maven+Ivy proxy is the way to go. For instance, the community build uses the proxy at "proxy-ch" to speed up builds, as in https://github.com/scala/community-builds/blob/master/common-2.11.x.conf#L144-l145
A possible caveat is in the use of the "/repo" virtual repository, which automatically aggregates all of the remote (proxy) repositories defined in Artifactory: as it is a well-known repository, random remote users with read access to the proxy machine may start using "/repo" for no special reason, adding to the server load. This is partly what happened with "repo.typesafe.com", which was incorrectly being used as proxy in this manner by everyone and their dog.
If the proxy is behind a firewall, that is not a problem. Otherwise, it may make sense to disable "/repo" and configure instead a repository group for the proxy repos with some different name, like "/cache" or something similar, just to obfuscate things a little. Ideally, access to the proxy repos and/or the group would be limited using username and password, but I don't think there is a straightforward support in sbt (hence in dbuild) for that. See https://github.com/sbt/sbt/issues/576 and https://github.com/sbt/sbt/issues/731.
From https://github.com/scala-ide/uber-build/pull/71 I understand you would need an Artifactory proxy running on EC2, on the (virtual) machines that run the build. The distributed nature of EC2 makes having a single proxy in this case a bit moot; however, nothing prevents you from having an Artifactory running on each executor. By default Artifactory runs using its own embedded Tomcat, so you can probably even limit the interface Tomcat listens on to localhost (or use ipchains for this purpose).
In any event, these are optimizations/security settings. In the simplest case, you can just run one Artifactory per executor (if they are long-lived), and use "/repo" as in the community build example.
These are the insights that I can give at the moment, I hope I understood the situation at hand correctly. Cheers!

**Comment by adriaanm** [comment]
Thanks! Is there a way you could dump the artifactory xml config and gist/email it?

**Comment by adriaanm** [comment]
I was going to run one artifactory on the same machine that runs jenkins (on an [m3 medium or large node](http://aws.amazon.com/ec2/instance-types/#m3)). I'll add 200GB of EBS (regular SSD) storage for the repo.

**Comment by cunei** [comment]
You can copy the full configuration of all the remote repositories defined on proxy-ch in one step: if you visit the Admin tab of Artifactory, under the "Remote Repositories" section there is an "Import" button. Use "https://proxy-ch.typesafe.com:8082/artifactory", and you should be good to go. If it complains about permissions, please write me on flowdock and we'll sort those out.

**Comment by adriaanm** [comment]
Closed by #50 and #62
