### ISSUE TITLE
allow community build to fail in release flow

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#199]
https://wiki.jenkins-ci.org/display/JENKINS/Build+Flow+Plugin#BuildFlowPlugin-Ignore

**Comment by SethTisue** [comment]
background: all of the community builds are failing right now for various reasons. fixes are in the works, but they often take days because they involve waiting on third parties, or waiting on multiple lengthy test runs, or waiting for multiple problems to accumulate since it's more efficient to work on several things together. this is likely to be a typical situation, ongoing, because the community build is perpetually fragile. (partly because of flaky tests and such, and partly because it often finds actual problems.) so it doesn't really make sense to prevent nightlies from being published anyway. (`integrate-bootstrap` does publish the maven artifacts regardless, but `release-main` does other stuff too)

we do still want to run the community build as part of release-main, but ignore the result. the build flow DSL offers a combinator for this (Adriaan's link). hopefully "ignore" and "retry" can be composed, because I've found it really convenient and helpful to have the 2 retries, to get some indication whether a failure is transient without having to manually trigger, and then wait for, a re-run.

**Comment by SethTisue** [comment]
related: integrate-windows is flaky, too (#217)

**Comment by SethTisue** [comment]
less sure about this currently. 2.11.x (and 2.11.x-jdk8) have been pretty smooth sailing lately, occasional fixes aside. 2.12.x has been failing for a while, but only because of a tricky regression that's taking a while to address. 2.13.x is still in early stages and forcing it green by just commenting stuff out is fine.

**Comment by SethTisue** [comment]
if someone just wants the last thing that got built, they can use the last integrate-windows job that succeeded (as recommended at e.g. http://stackoverflow.com/questions/40622878/how-do-i-tell-sbt-to-use-a-nightly-build-of-scala-2-11-or-2-12/). it may actually make sense to retain a higher bar for integrate-main.

**Comment by SethTisue** [comment]
the community build is out of the release flow. it was an interesting experiment.
