### ISSUE TITLE
forward merge nightly

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-jenkins-infra#250]
Merge 2.12.x into 2.13.x and run nightly. So that we can do the merge manually to resolve conflicts as soon as they arise

**Comment by SethTisue** [comment]
the rate of change on 2.12.x has slowed down to the point where this almost certainly isn't worth it IMO

**Comment by dwijnand** [comment]
And yet we shy away from doing the branch merge in favour of cherry-forward-picking changes we want ASAP in both branches because of the possibly large cost in undertaking a branch merge.

... but I would look to set this up as a Travis CI (or GitHub Actions) nightly rather than a Jenkins one, b/c it's easier.

**Comment by SethTisue** [comment]
(Feel free to transfer the ticket to scala-dev and re-open, if you like.)
